### PR TITLE
feat(servers_config): add require statement to manage dependencies

### PR DESCRIPTION
**Pull request by javierbertoli**
Also, check config before applying

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [X] `[feat]`     A new feature
- [X] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

This let's you add dependencies on other resources being applied for a particular vhost

A common case is when you use this formula together with letsencrypt's, validating
through nginx: you need nginx running (to validate the vhost) but can't have the ssl
vhost up until the certificate is validated (because it won't exist and will
make nginx fail to load the configuration)

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [X] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by aboe76** [comment]
@javierbertoli I'm missing the `requires` test it's only mentioned in pillar.example but not in the test.

**Comment by javierbertoli** [comment]
Sorry, I got sidetracked. @aboe76 any suggestion of a comprehensive test for the `requires` introduced here? I'm not sure I can think of anything meaningful

**Comment by aboe76** [comment]
@javierbertoli, I'm not sure either, maybe something with certificates.sls?

**Review by aboe76 — APPROVED** [review]

**Comment by javierbertoli** [comment]
@aboe76 added some tests and they pass, so I'll merge. Thanks!

**Pull request merged**
