### PR TITLE
implement test harness

### PR DESCRIPTION
**Pull request by meganlkm**
Implement the [formula-test-harness](https://github.com/intuitivetechnologygroup/formula-test-harness). I included a travis config if you want to set that up too.

### CODE REVIEW

**Comment by javierbertoli** [comment]
Hi @meganlkm, can you point me to some formulas testing done with [formula-test-harness](https://github.com/intuitivetechnologygroup/formula-test-harness) as to see the usage? I followed the link but found no examples.

I'm personally more familiar with the [kitchen-ci](https://kitchen.ci/) testing harness, using the [kitchen-salt]( https://github.com/saltstack/kitchen-salt) provisioner and [inspec](https://www.inspec.io/), which seem **to me** [simpler to use](https://github.com/saltstack-formulas/packages-formula/tree/master/test/integration/default)  and [inplement](https://github.com/saltstack-formulas/packages-formula/blob/master/.kitchen.yml). They're currently [being used across many fomulas](goo.gl/9S6epS) and are being activelly maintained and widely used.

But, that said, I'm totally opened to new tools and ideas, so some examples will let me compare and, perhaps, adopt it :smile:

**Comment by meganlkm** [comment]
Here are a few examples:

https://github.com/meganlkm/gpg-formula
https://github.com/intuitivetechnologygroup/sqlite-formula
https://github.com/saltstack-formulas/uwsgi-formula
https://github.com/intuitivetechnologygroup/credstash-formula (still in dev)
https://github.com/intuitivetechnologygroup/authconfig-formula/pull/44

**Comment by meganlkm** [comment]
it was also demoed in a recent meetup: https://github.com/intuitivetechnologygroup/saltstack-meetup-2018-03-13

**Comment by meganlkm** [comment]
There are also no tests currently implemented for this formula. It would be beneficial to have at least __a__ test in place for this as it is a popular formula.

**Comment by blbradley** [comment]
Hello!

I would suggest setting up Travis and getting the test suite passing for each formula in this ecosystem where this has been proposed before merging.

If you didn't create the formula yourself, you'll have to ask someone with on the 'Core' team to enable Travis per formula.

**Comment by javierbertoli** [comment]
In the examples above, do I undestand correctly that the harness just runs the formula in a container and checks that the output has no failures? I see no actual tests there (like *is the service really running? and listening in the desired port?*). Ie, the state modifying the config file can modify the config and produce a file that would let the service run, but would be totally useless. The harness just seems to check the states run OK, but not if they produce the correct results.

Using the tools I mention, implementing the harness here would require a `.kitchen.yml` file like [this one](https://github.com/saltstack-formulas/packages-formula/blob/master/.kitchen.yml) and then tests can be written in files [like these](https://github.com/saltstack-formulas/packages-formula/tree/master/test/integration/default). And the tests look like [these in travis](https://travis-ci.org/saltstack-formulas/packages-formula/jobs/353315165#L8195-L8234) or locally.

I'd be grateful if you can point me to tests that work in a similar fashion to the ones I point above, to see how to implement them, as that's what I'd like to do in testings.

**Comment by simplyadrian** [comment]
The test suites are dynamically recognized and run in untainted containers. You can have as many test suites as you need. The example/default test is a pytest however, the test harness is flexible enough to run most other kinds of tests. Additionally, but less important, seeing as this is a python project it seems strange to be using a ruby/chef test harness which is not simple to use nor clearly documented in the salt documentation. (yes, I have seen this https://saltstack.com/testing-your-salt-states-with-kitchen-salt/).

**Comment by blbradley** [comment]
Personally, I've had _great_ results when using Test Kitchen to test formulae in this ecosystem. In addition, Testinfra can be used to write system level tests in Python.

**Comment by javierbertoli** [comment]
> Additionally, but less important, seeing as this is a python project it seems strange to be using a ruby/chef test harness which is not simple to use nor clearly documented in the salt documentation

@simplyadrian, for what I've seen through the years, the reason they're used is that [kitchen-ci](https://kitchen.ci/) is a mature testing harness which lets you use different drivers to run the same tests in different platforms, like docker, vagrant, aws, openstack, etc (a huge plus). Even [SaltStack](https://github.com/saltstack/salt/blob/develop/.kitchen.yml) uses it for testing. 

For the same reason, [Inspec](https://www.inspec.io/) which is a fork of [Serverspec](http://serverspec.org/) is becoming a somewhat *de facto* standard for testing. Although maintained by the Chef community, is quite powerful for compliance and security testing, which lets you run the tests both locally or remotely, on already running hosts.

Or, as @blbradley says, you can use [Testinfra](https://testinfra.readthedocs.io/) if you want to write your tests in Python.

All these tools are plugable, through drivers, provisioners and verifiers.

> a ruby/chef test harness which is not simple to use nor clearly documented

In this point I disagree with you, both [are fairly easy to use](https://github.com/saltstack-formulas/postfix-formula/pull/66/files), and widely documented.

The [kitchen-salt provisioner](https://kitchen.saltstack.com/)'s options are [described here](https://kitchen.saltstack.com/docs/file/docs/provisioner_options.md).

> The test suites are dynamically recognized and run in untainted containers. You can have as many test suites as you need. The example/default test is a pytest however, the test harness is flexible enough to run most other kinds of tests.

 Can I use other drivers but docker, ie to test AWS specifics? How can I plug Inspec or Testinfra tests to formula-test-harness? Can you provide me with some examples?

As I said in my original question, I'm not against new tools, nor I'm trying to disrespect or dismiss the formula-test-harness project. I just want some examples, to evaluate the benefits over existing tools and to consider if I jump to this new tool :smile:

**Comment by meganlkm** [comment]
It's an opensource project. Make it so. As previously mentioned, there are currently zero tests for this project.

**Comment by aboe76** [comment]
@meganlkm I have merged your pr, could you see about the errors?

**Comment by aboe76** [comment]
@meganlkm can you take a look at why the pytests fail with an assertion error?

**Pull request merged**
