### PR TITLE
Add ca certificate option

### PR DESCRIPTION
**Pull request by amontalban**
This PR address the problem when you want to have only a file containing the CA certificate or chain to be used by [ssl_stapling](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling) feature.

### CODE REVIEW

**Comment by EvaSDK** [comment]
Why not use nginx:ng:certificates:public_cert ? the corresponding private key is not mandatory. This is what I run in production for handling stapling.

**Comment by amontalban** [comment]
Sounds good, didn't thought about that approach. Should I close this or leave it open for more reviews?

**Comment by EvaSDK** [comment]
It's up to you and formula maintainers. If you are satisfied with my suggestion, I guess you could indeed close this PR.

**Comment by amontalban** [comment]
I ended up using `nginx:ng:certificates:public_cert` as @EvaSDK recommended. Thanks 👍

**Pull request closed without merging**
