### PR TITLE
Make certificates path configurable.

### PR DESCRIPTION
**Pull request by abednarik**
Simple but useful change for us, make configurable path to save ssl certificates.

### CODE REVIEW

**Comment by aboe76** [comment]
@abednarik good idea, could you update the pillar.example file so it is documented.

**Comment by abednarik** [comment]
HI @aboe76 

 Thanks for your feedback. Can you please check if that example if fine? If not, please let me know.

Cheers.

**Comment by aboe76** [comment]
@abednarik thanks for the fix

**Comment by abednarik** [comment]
Thanks you for the quick response.

Cheers.

**Pull request merged**
