### PR TITLE
Promote nginx:ng to nginx

### LINKED ISSUE #230: BREAKING CHANGE: Replace old `nginx` with `nginx.ng` (v1.0.0)
The introduction of `semantic-release` in #229 paves the way for this formula to remove the old `nginx` configuration and to replace it with `nginx.ng`.

### PR DESCRIPTION
**Pull request by daks**
The so long-awaited BREAKING CHANGE of replacing `nginx` by `nginx.ng`! :)

Fixes #230

### CODE REVIEW

**Comment by myii** [comment]
@daks I haven't had a look yet but this is going to be awesome!  We may have to rename the formula to `daks-formula`!  OK, I'm exaggerating a bit but you get the idea...

**Comment by myii** [comment]
`default-fedora-28-2018-3-py2` failed due to `10m` inactivity but I gave it a boot and now all tests are passing.  I've also had a quick scan across the diff and nothing is jumping out at me.  It looks like we're on the way to a winner, here!

**Comment by daks** [comment]
Any opinion about the commit message for this big change? or the 'BREAKING CHANGE' message? I'm open to suggestions to improve it.

**Comment by myii** [comment]
@daks How about something like:

```git
BREAKING CHANGE: all pre-existing configurations must be reviewed;
`nginx.ng` must be promoted to `nginx` and any uses of the original
`nginx` will have to be converted.
```

**Comment by daks** [comment]
commit message changed. 
For me, PR is finished, can be merged when you're ready.

**Comment by myii** [comment]
@daks Thanks to the reviews by @noelmcloughlin and @aboe76, I reckon we're ready to merge on this one.  Do you have any other changes to make or shall I go ahead?

**Comment by daks** [comment]
@myii for me, it's ready to merge.

**Comment by myii** [comment]
@daks OK, we were typing at the same time as each other!  I'll hit the merge as soon as the CI run completes.

**Comment by daks** [comment]
Thanks @myii for the merge! A great milestone for this formula! :)

**Comment by myii** [comment]
You're welcome, @daks!  Brace for impact!

**Pull request merged**
