### PR TITLE
test(inspec): more tests on nginx config

### PR DESCRIPTION
**Pull request by daks**
Some more tests on config files generated: snippets and sites

### CODE REVIEW

**Comment by myii** [comment]
@daks The new testing matrix is doing it's job!  So the tests are passing for Debian and Ubuntu but not the other platforms.

**Comment by daks** [comment]
Yes, I wrote those naively, based on Debian knowledge. I now need to adapt them to other platforms, looking at the code.

**Comment by daks** [comment]
After disabling OpenSuse42 tests, all pass.

**Comment by myii** [comment]
@daks Fantastic work.  If `opensuse` can't be fixed, this is ready to be merged, right?  In the meantime, @aboe76 do you have any suggestions about how we can get it working?  The last failing log [is here](https://travis-ci.com/saltstack-formulas/nginx-formula/jobs/192706557).

**Comment by daks** [comment]
@myii for me, it's ok to merge without opensuse

**Comment by daks** [comment]
@myii can you refresh my memory about this PR and what is still missing?

**Comment by myii** [comment]
@daks Just need to append this commit: https://github.com/myii/nginx-formula/commit/3fa262bdb90f27bff197bf2c53438ddf5c38420b.

**Comment by myii** [comment]
Brilliant @daks, thanks for this beneficial PR!  Merged.

**Comment by daks** [comment]
Thanks for merging and for solving opensuse :)

**Pull request merged**
