### PR TITLE
RedHat uses /var/run, not /run

### PR DESCRIPTION
**Pull request by stromnet**
Hi,

a minor fix for RedHat.

Regards
Johan

### CODE REVIEW

**Comment by iggy** [comment]
You'd save the extra grains.filter_by if you put something like piddir in the lookup section and then changed the sls files to use {{ piddir }}/nginx.pid

**Comment by stromnet** [comment]
That does not seem to apply to this particular formula.

nginx/ng/files/nginx.conf is built purely from nginx/ng/map.jinja (via nginx/ng/config.sls), without any specific directives at all.
Neither nginx/ng/files/nginx.conf or nginx/ng/config.sls have any specific directives for pidfile or anything else, so I don't see how that would be done? I'm pretty new to salt so I might have missed something though!

**Comment by iggy** [comment]
Okay... There's a reason I avoid these "ng" formulas like the plague.

**Comment by puneetk** [comment]
We cant automatically merge this pull request, can you please rebase your pull request or at least 

```
git pull https://github.com/saltstack-formulas/nginx-formula master
git commit 
git push 
```

**Comment by stromnet** [comment]
Rebased and simplified with new pid_file lookup

**Pull request merged**
