### PR TITLE
Minor bugfix and updated pillar.example

### PR DESCRIPTION
**Pull request by TaiSHiNet**

### CODE REVIEW

**Comment by nmadhok** [comment]
@gravyboat Can you please review this?

**Comment by TaiSHiNet** [comment]
Just fixed a key issue, testing live now.

**Comment by TaiSHiNet** [comment]
@gravyboat Don't merge this just yet, I'm adding a few extra features

**Comment by TaiSHiNet** [comment]
@gravyboat it should be fine now. Figured it out that mainline version lacked full builds, which led me to add another ppa version

**Pull request merged**
