### PR TITLE
Add feature to configure extra files from pillar

### PR DESCRIPTION
**Pull request by amontalban**

### CODE REVIEW

**Comment by aboe76** [comment]
this could be done already with the current setup:
```
nginx:
  ng:
    servers:
      managed:
        http_options.conf:
          enabledd: False
          available_dir: /usr/local/etc/nginx
          config:
            - sendfile: 'on'
            - tcp_nopush: 'on'
            - tcp_nodelay: 'on'
            - send_iowait: 12000
```

**Comment by amontalban** [comment]
Hi @aboe76,

Thanks for clarification, what I wanted to do is to be able to have big files imported directly instead of using keys for each setting because it's easier to maintain.

Do you know if there is a way to support either keys or inline content?

Thanks!

**Comment by amontalban** [comment]
I have tried to use the pillar:

```sls
nginx:
  ng:
    servers:
      managed:
        http_options.conf:
          enabled: False
          available_dir: /usr/local/etc/nginx
          config:
            - sendfile: 'on'
            - tcp_nopush: 'on'
            - tcp_nodelay: 'on'
            - send_iowait: 12000
```

And produced:

```
          ID: server_state_0
    Function: file.absent
        Name: /usr/local/etc/nginx/sites-enabled/http_options.conf
      Result: True
     Comment: File /usr/local/etc/nginx/sites-enabled/http_options.conf is not present
     Started: 07:10:21.626340
    Duration: 0.541 ms
     Changes:   
```

Changed `enabled: False` to `enabled: True` and here is the output:

```
          ID: server_conf_0
    Function: file.managed
        Name: /usr/local/etc/nginx/http_options.conf
      Result: True
     Comment: File /usr/local/etc/nginx/http_options.conf updated
     Started: 07:14:18.468458
    Duration: 23.314 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: server_state_0
    Function: file.symlink
        Name: /usr/local/etc/nginx/sites-enabled/http_options.conf
      Result: True
     Comment: Created new symlink /usr/local/etc/nginx/sites-enabled/http_options.conf -> /usr/local/etc/nginx/http_options.conf
     Started: 07:14:18.492279
    Duration: 1.864 ms
     Changes:   
              ----------
              new:
                  /usr/local/etc/nginx/sites-enabled/http_options.conf
```

I don't want the last symlink, do you know if that's something I can do with pillars or should I submit a PR to fix that?

Thanks!

**Comment by amontalban** [comment]
Ok I have found the solution, going to create a new PR. Thanks!

**Pull request closed without merging**
