### PR TITLE
Remove defaults, they are set even if you do not need them

### PR DESCRIPTION
**Pull request by amontalban**
In my case

### CODE REVIEW

**Comment by abednarik** [comment]
I agree here, setting defaults in the formula not present in Nginx default config [ https://github.com/nginx/nginx/blob/master/conf/nginx.conf ]  is not a good idea.

**Comment by aboe76** [comment]
@amontalban is this only to have nginx.ng not touch nginx.conf?

Isn't it easier to make switch to say leave nginx.conf alone instead of removing default config that might not be set on other distro's ?

**Comment by amontalban** [comment]
@aboe76 I have a custom nginx.conf file and some default settings are included in extra files which makes service to not start because of duplicated entries:

```
user www;
worker_processes 22;
worker_rlimit_nofile 100000;

# [ debug | info | notice | warn | error | crit ]
error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections 10240;
    use kqueue;
    kqueue_changes 2048;
}


http {
    include http_options.conf;
    include virtual_servers.conf;
    include default.conf;
}
```

So in my case I need nginx.conf to be managed but to not include defaults, probably a corner case? Not sure how common this is.

Thanks!

**Comment by aboe76** [comment]
@amontalban why does nginx.conf and your extra files have duplicate entries? isnt' it easier to leave remove the duplicates from the extra files?

**Comment by amontalban** [comment]
@aboe76 alright I will go ahead and close this since I'm porting my configs to this formula. Thanks!

**Pull request closed without merging**
