### PR TITLE
touch htpasswd file if it doesn't exist

### LINKED ISSUE #70: nginx.users does not take effect for htauth file is not exist.
In salt-contrib's module basicauth.py https://github.com/saltstack/salt-contrib/blob/master/modules/basicauth.py#L23-L26

```python
"""
...
The htpasswd file must exist in order to successfully 
add and delete users. You can create a new empty file as follows::

    touch /etc/.htpasswd
...
"""
```

It will be ok, when create file after htpasswd installed and before basicauth.adduser.
``` yaml
htauth:
  file.managed:
    - name: {{ htauth }}
```

### PR DESCRIPTION
**Pull request by arthurlogilab**
Fixes #70

### CODE REVIEW

**Comment by gravyboat** [comment]
Thanks.

**Comment by codyaray** [comment]
Looks like this just fails if it doesn't exist, rather than touching/creating it.

```
----------
          ID: make sure /etc/nginx/.htpasswd exists
    Function: file.exists
        Name: /etc/nginx/.htpasswd
      Result: False
     Comment: Specified path /etc/nginx/.htpasswd does not exist
     Started: 16:39:46.020160
    Duration: 1.104 ms
     Changes:
```

**Comment by arthurlogilab** [comment]
@codyaray you're right, although I'm not sure I want that file to be touched on every highstate that is run. In my use case I prefer to have an error that tells me that I need to generate or create this file.

**Comment by codyaray** [comment]
So you really want a create-if-not-exists, right? Something like this
should work:

```
touch /etc/nginx/.htpasswd:
  cmd.run:
    - creates: /etc/nginx/.htpasswd
```

**Pull request merged**
