### PR TITLE
test(inspec): switch tests to use Inspec

### PR DESCRIPTION
**Pull request by daks**
After discussion on slack, a PR to switch to tests with Inspec. Those are basics, testing pkg/file/service.
General CI config copied from https://github.com/saltstack-formulas/template-formula/ master, so commitlint included.

### CODE REVIEW

**Comment by javierbertoli** [comment]
Awesome. I'd probably remove the ` test/salt/default/pillar/nginx.sls` and `Gemfile.lock` files?

**Comment by daks** [comment]
Files removed.

**Comment by daks** [comment]
CentOS 7 test disabled for now, but it's still better than no tests at all :champagne:

**Comment by myii** [comment]
@daks Merged -- thanks for fixing the tests in this formula.  A very impressive job, as we've already discussed on Slack.  Just to bring across the important notes here:

* [x] Left `semantic-release` (and `commitlint`) for a future PR.
* [x] Used the newest testing matrix from `salt-formula` instead of the `template-formula`, as based on this merged PR by @javierbertoli: https://github.com/saltstack-formulas/salt-formula/pull/406.
* [ ] Disabled the Salt version-specific test suites for the time being (using `default` throughout) -- need to create an issue to remind us that this work is still needed.
* [ ] Commented out `centos-7` because it is currently failing (on the `salt-formula` as well, since around 4 days ago) -- Daniel mentioned probably due to work being done on releasing python3.6 versions of salt for centos 7 -- need to create an issue to retest this in the next week or so.

**Pull request merged**
