### PR TITLE
Choose mainline/stable from ppa at will

### PR DESCRIPTION
**Pull request by TaiSHiNet**

### CODE REVIEW

**Comment by gravyboat** [comment]
Good change, could you please add that `ppa_version` to the example pillar in case users want to overwrite it?

**Comment by nmadhok** [comment]
@TaiSHiNet Just noticed that you haven't added ppa_version to pillar.example. Can you create another PR with the change?

**Comment by TaiSHiNet** [comment]
@gravyboat Just did, requesting pull now

**Comment by nmadhok** [comment]
@gravyboat Sorry just noticed your comment on this PR after the merge.

**Comment by TaiSHiNet** [comment]
No prob, new pull should work fine

**Comment by TaiSHiNet** [comment]
@gravyboat @nmadhok I might be uploading a newer version today, lesser lines and should give more choices overall

**Comment by nmadhok** [comment]
@TaiSHiNet will wait for the PR.

**Pull request merged**
