### PR TITLE
Replace the term vhost for server everywhere and solve issue #105

### PR DESCRIPTION
**Pull request by renich**
So, here's the pull request. I don't know if there are any integration tests to run or anything.

Let me know what you think.

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks good to me, thanks! Since this is a backwards incompatible change I'm going to let it sit in case anyone else wants to review it.

**Comment by renich** [comment]
@gravyboat awesome. Thanks.

**Comment by renich** [comment]
@gravyboat  ping

**Comment by gravyboat** [comment]
Thanks!

**Comment by renich** [comment]
Your welcome :)

**Pull request merged**
