### PR TITLE
feat(context): pass `nginx` to snippets and server_config contexts

### PR DESCRIPTION
**Pull request by sticky-note**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [x] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

pass `nginx` to `snippets` and `server_config` contexts

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by vutny — APPROVED** [review]
Seems to be useful, thanks.

**Review by aboe76 — APPROVED** [review]
I see no issues

**Comment by myii** [comment]
Shouldn't be a problem however we have had a report about memory issues when passing full dicts by context:

* https://github.com/saltstack-formulas/apache-formula/issues/297

Something we need to consider in the long run.

**Comment by aboe76** [comment]
@myii I think you are right, about that considering the memory issues. especially on large configurations.

**Comment by sticky-note** [comment]
That's exactly why I waited for a review @myii

**Comment by sticky-note** [comment]
@vutny @myii @aboe76,
Seems to consume significantly less RAM on sls rendering with:
```
{%- set _nginx = nginx.copy() %}
{%- do _nginx.pop('snippets') %}
{%- do _nginx.pop('servers') %}
```

@myii Ok to merge like that ?

**Review by noelmcloughlin — APPROVED** [review]
Updated PR looks fine to me.
I done something similar in https://github.com/saltstack-formulas/apache-formula/pull/299

**Pull request merged**
