### PR TITLE
Require NGINX unit file when starting service

### PR DESCRIPTION
**Pull request by grobinson-blockchain**

### CODE REVIEW

**Comment by gravyboat** [comment]
Was this failing for you without the service file in place?

**Comment by grobinson-blockchain** [comment]
I'm experiencing race conditions where we attempt to start NGINX prior to finishing the installation/configuration:

    nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
    nginx: [emerg] open() "/var/log/nginx/access.log" failed (2: No such file or directory)

which causes the service state to fail:

          ID: nginx_service
    Function: service.running
        Name: nginx
      Result: False
     Comment: Service nginx has been enabled, and is dead
     Started: 16:25:08.690522
    Duration: 234.573 ms
     Changes:
              ----------
              nginx:
                  True

I'm investigating it - I thought I had found the issue but hadn't - will update the pull request when isolated and confirmed fixed.

**Comment by gravyboat** [comment]
Sounds good. Ping me again when you are ready.

**Comment by grobinson-blockchain** [comment]
Wow.. so it appears that an `extend` I have on another service (such that it waits for NGINX to start before it starts itself) causes NGINX to start too soon:

    extend:
      consul-template-nginx-service:
        service.running:
          - require:
            - service: nginx_service

Could this be a bug in salt?

**Comment by gravyboat** [comment]
Huh, maybe? Can you do a full output and follow the trace through to see if all the states in the file are being called in the proper order?

**Pull request closed without merging**
